### ISSUE TITLE
declare modifier required

### ISSUE THREAD

**Issue by D4nte** [badrap/result#1]
Hi,

I am not sure how you generate `index.d.ts` but it seems there is an issue with it as I get the following error when running `tsc`:

```
$ tsc
node_modules/@badrap/result/dist/index.d.ts:1:1 - error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.

1 abstract class _Result<T, E extends Error> {
  ~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
```

**Comment by jviide** [comment]
Hm, that's weird, as the `index.d.ts` should be generated by the TypeScript compiler machinery. Which version of `tsc` are you running?

**Comment by jviide** [comment]
A (potentially) fixed version of @badrap/result has now been published as v0.2.5. Does this work for you?

Indeed, the TypeScript compiler should have added `declare` modifiers to `index.d.ts`, but for some reason didn't - potentially this is related to https://github.com/Microsoft/TypeScript/issues/28995. I recompiled @badrap/result with TypeScript v3.4.5, and the `declare`s now appear to be where they should.

Apparently some newer versions of TypeScript don't mind using `index.d.ts` with the missing modifiers, which is why we didn't get hit by this bug. Thanks for pointing this out!

**Comment by D4nte** [comment]
yep looks fixed to me. Thanks!

**Comment by jviide** [comment]
Great! Thanks for reporting this.
